accounts/urls.py
from django.urls import path

from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='flogin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url='/standard-accounts/password_reset/done/'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
    success_url='/standard-accounts/reset/complete/'), name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
    success_url='/standard-accounts/password_change/done/'),
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='my_account'),
]

testwagtail/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from simple_forum import urls as forum_urls
from accounts import urls as accounts_urls
from translate_tutor import urls as translate_tutor_urls
from captcha import urls as captcha_urls

from search import views as search_views
from blog import views as blog_views

from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    # url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^forum/', include(forum_urls)),
    url(r'^standard-accounts/', include((accounts_urls, 'accounts'), namespace='standard-accounts')),
    # url(r'^standard-accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include(tf_urls)),
    # path('captcha/', include('captcha.urls')),
    path('captcha/', include(captcha_urls)),


    url(r'^search/$', search_views.search, name='search'),
    url(r'^index/indent/$', blog_views.indent, name='indent'),
    url(r'^translate/', include(translate_tutor_urls)),


    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(translate_tutor_urls)),
    url(r'^wt/', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput)
    captcha = CaptchaField(label='Are you an human? ')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'captcha')

accounts/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm  # add emeil
from django.contrib.auth import login as auth_login

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('two_factor:profile')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'accounts/my_account.html'
    success_url = reverse_lazy('my_account')

    def get_object(self):
        return self.request.user


# def password_reset_complete(request):
#     return render(request, 'accounts/password_reset_done.html')


def password_change_done(request):
    return render(request, 'accounts/password_change_done.html')

accounts/templates/accounts/accounts_base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}App{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'simple_forum/css/app.css' %}">
    <link rel="icon" type="image/png" href="{% static 'translate_tutor/img/zion.png' %}" /> {#decided Not Found:/favicon.ico#}
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'simply_first' %}">Forum</a>
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'standard-accounts:my_account' %}">My account</a>
                    <a class="dropdown-item" href="#">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'standard-accounts:logout' %}">Log out</a>
                  </div>
                </li>
              </ul>
            {% else %}
                <form class="form-inline ml-auto">
                  <a href="{% url 'two_factor:login' %}" class="btn btn-outline-secondary">Log in</a>
                  <a href="{% url 'standard-accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
            {% endif %}
          </div>
        </div>
      </nav>

      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
  {% block javascript %}{% endblock %}
  </body>
</html>

accounts/templates/accounts/base_accounts.html
{% extends 'simple_forum/forum_base.html' %}
{% load static%}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'simply_first' %}">Forum</a>
        </h1>
        {% block content %}

        {% endblock %}
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}
{% load static %}

{% block title %}
  Log in to Forum
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">Log in</h2>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'simple_forum/includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            New to Forum? <a href="{% url 'standard-accounts:signup' %}">Sign up</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="#" class="text-muted">Forgot your password?</a>
          </small>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/my_account.html
{% extends 'accounts/accounts_base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'simple_forum/includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'accounts/accounts_base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'simple_forum/includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'accounts/accounts_base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'standard-accounts:password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'simply_first' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Reset your password</h3>
                    <p>Enter your email address and we will send you a link to reset your password.</p>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% include 'simple_forum/includes/form.html' %}
                        <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'two_factor:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'simple_forum/includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'standard-accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'two_factor:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'standard-accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Forum username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Forum Team

accounts/templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}

{% load static form_tags widget_tweaks %}

{% block title %}
  Sing up to Forum
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h2>Sign up</h2>
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'simple_forum/includes/form.html' %}
                <button type="submit" class="btn btn-primary">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'two_factor:login' %}">Log in</a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}